import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/authContext";
import { TodoProvider } from "@/context/todoDataContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <TodoProvider>
        {children}
        </TodoProvider>
        </AuthProvider>
        </body>
    </html>
  );
}
